### ISSUE TITLE
npm run build gives me an error

### ISSUE THREAD

**Issue by bitcoinvsalts** [cyyyu/firetodo#1]
When I run npm run build I get the following result, any idea why?

```
public\App.d90b2eeb.map                       0 B    82.93s
    at Bundler.bundler.on (C:\Users\herve\Documents\GitHub\firetodo\node_modules\parcel-plugin-sw-precache\index.js:35:43)
    at emitOne (events.js:116:13)
    at Bundler.emit (events.js:211:7)
    at Bundler.bundle (C:\Users\herve\Documents\GitHub\firetodo\node_modules\parcel-bundler\src\Bundler.js:288:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
```

**Comment by bitcoinvsalts** [comment]
this issue happened because I used yarn instead of npm. issue fixed. thanks for this repo.

**Comment by cyyyu** [comment]
good ro know😄
